### ISSUE TITLE
Installation instruction

### ISSUE THREAD

**Issue by kevinbsc** [makeyourowntextminingtoolkit/makeyourowntextminingtoolkit#1]
Is there an instruction available for installation? Thanks for making the codes (SVD) available.

**Comment by makeyourowntextminingtoolkit** [comment]
Hi @kevinbsc at the moment the code is still developing and very much experimental

You can follow progress on the blog [makeyourowntextminingtoolkit.blogspot.co.uk](https://makeyourowntextminingtoolkit.blogspot.co.uk)

You can see examples of how to use the tools, such as the SVD functionality, in the python notebooks also here in this GitHub repository

To install, all you need to do is download (or clone) the repository and ensure that the library is findable by the python import command (such as in the local directory)

I hope that helps, if not ping me back.
